export const APARTMENTS = {
  GET_APARTMENTS: "GET_APARTMENTS",
  ADD_APARTMENT_TO_FAVORITES: "ADD_APARTMENT_TO_FAVORITES",
  REMOVE_APARTMENT_TO_FAVORITES: "REMOVE_APARTMENT_TO_FAVORITES",
  REJECTED_APARTMENT: "REJECTED_APARTMENT",
  UPDATE_APARTMENTS: "UPDATE_APARTMENTS",
  GET_CITIES: "GET_CITIES",
  UPDATE_DATA: "UPDATE_DATA"
};

export const LOADING = {
  UPDATE_LOADING: "UPDATE_LOADING"
};

export const USER = {
  GET_USER_INFO: "GET_USER_INFO",
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER"
};
